drop table if exists news;
drop table if exists content;
drop type if exists content_type;

CREATE TABLE news (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    info TEXT NOT NULL,
    author VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE content_type AS ENUM ('novel', 'video');

CREATE TABLE content (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    type content_type NOT NULL,
    url TEXT NOT NULL 
);

-- Inserindo dados fictícios para a tabela news
INSERT INTO news (title, info, author, created_at, updated_at) VALUES 
('Lançamento do novo sistema de streaming da Globo', 'A Globo anuncia hoje seu novo serviço de streaming com conteúdo exclusivo e produções internacionais.', 'Carlos Drummond', '2025-01-15 09:30:00', '2025-01-15 09:30:00'),
('Novela "Mar de Paixões" bate recorde de audiência', 'Com mais de 35 pontos no IBOPE, a novela das nove se torna líder absoluta de audiência em 2025.', 'Ana Beatriz Silva', '2025-02-10 20:15:00', '2025-02-10 21:30:00'),
('Globoplay expande catálogo com produções independentes', 'Novos filmes e séries de produtores independentes chegam à plataforma este mês.', 'Rafael Oliveira', '2025-03-05 14:20:00', '2025-03-05 14:20:00'),
('Estreia de reality show causa polêmica nas redes sociais', 'O novo reality show "Desafio Extremo" dividiu opiniões entre os espectadores logo em seu primeiro episódio.', 'Mariana Costa', '2025-03-22 08:45:00', '2025-03-22 10:15:00'),
('Grande Final do BBB 2025 tem recorde de votação', 'Mais de 500 milhões de votos foram computados para decidir o vencedor da 25ª edição do reality.', 'Pedro Almeida', '2025-04-15 23:10:00', '2025-04-16 00:30:00'),
('Novo documentário sobre meio ambiente recebe prêmio internacional', 'Produção da Globo sobre Amazônia é reconhecida no Festival de Documentários de Berlim.', 'Juliana Santos', '2025-04-30 16:45:00', '2025-04-30 18:20:00'),
('Mudanças na programação matinal da TV Globo', 'Nova atração substituirá programa tradicional nas manhãs a partir de setembro.', 'Felipe Mendes', '2025-05-12 11:30:00', '2025-05-12 11:30:00'),
('Série brasileira é indicada ao Emmy Internacional', '"Fronteiras Invisíveis" concorre em três categorias no prêmio mais importante da televisão mundial.', 'Luciana Ferreira', '2025-06-03 09:15:00', '2025-06-03 14:40:00'),
('Novo aplicativo da Globo integra todas as plataformas', 'Usuários poderão acessar streaming, notícias e esportes em um único lugar.', 'Paulo Vieira', '2025-06-17 13:25:00', '2025-06-17 13:25:00'),
('Jornal Nacional comemora 60 anos no ar', 'Edição especial reúne todos os apresentadores da história do telejornal.', 'Renata Vasconcellos', '2025-07-05 20:30:00', '2025-07-05 21:45:00'),
('Transmissão das Olimpíadas de 2028 bate recorde de audiência', 'Mais de 150 milhões de brasileiros acompanharam alguma competição pela TV Globo.', 'Galvão Bueno', '2025-07-19 19:00:00', '2025-07-19 19:00:00'),
('Estúdios Globo inauguram nova cidade cenográfica', 'Novo espaço em Jacarepaguá é o maior complexo audiovisual da América Latina.', 'Boninho', '2024-12-10 10:15:00', '2024-12-10 10:15:00'),
('Globo Play adiciona legendas em 10 novos idiomas', 'Streaming brasileiro agora pode ser assistido com legendas em mandarim, árabe e hindi.', 'Carla Dantas', '2024-11-22 15:40:00', '2024-11-22 15:40:00'),
('Teledramaturgia da Globo é tema de exposição em Nova York', 'O MoMA abre mostra sobre a história das novelas brasileiras e sua influência global.', 'Roberto Irineu Marinho', '2024-10-20 11:30:00', '2024-10-20 11:30:00'),
('App GloboNews agora permite personalização completa', 'Usuários podem selecionar temas de interesse e receber notificações customizadas.', 'Míriam Leitão', '2025-01-08 16:45:00', '2025-01-08 16:45:00'),
('Plantão da Globo interrompe programação com descoberta científica', 'Anúncio sobre cura de doença rara gera pico de audiência em horário incomum.', 'William Bonner', '2025-04-02 13:15:00', '2025-04-02 13:15:00'),
('Festival de música da Globo reúne artistas de 20 países', 'Evento transmitido ao vivo para todo o Brasil celebra a diversidade musical mundial.', 'Anitta', '2025-02-18 19:30:00', '2025-02-18 19:30:00'),
('Canal infantil da Globo lança programa educativo premiado', '"Aprendendo com Diversão" recebe reconhecimento internacional por método inovador.', 'Xuxa Meneghel', '2024-12-10 10:30:00', '2024-12-16 14:25:00'),
('Minissérie histórica da Globo é adquirida por 30 países', 'Produção sobre período colonial brasileiro será exibida na Europa, Ásia e América do Norte.', 'Aguinaldo Silva', '2025-01-25 15:45:00', '2025-01-25 15:45:00'),
('Debate político da Globo estabelece novo formato', 'Candidatos terão direito a fact-checking em tempo real durante confrontos.', 'Maria Beltrão', '2025-04-08 21:30:00', '2025-04-08 23:15:00'),
('Globo Repórter especial sobre longevidade viraliza nas redes', 'Episódio sobre centenários brasileiros é o mais compartilhado da história do programa.', 'Glória Maria', '2025-02-14 22:00:00', '2025-02-15 08:30:00'),
('Nova plataforma de podcasts da Globo ultrapassa 1 milhão de assinantes', 'GloboPod consolida-se como líder no mercado de áudio no Brasil.', 'Marcos Mion', '2025-05-02 11:15:00', '2025-05-02 11:15:00'),
('Reportagem investigativa da Globo leva a mudança na legislação', 'Série de reportagens sobre corrupção resulta em aprovação de nova lei no Congresso.', 'Roberto Cabrini', '2024-10-18 18:40:00', '2024-11-22 09:10:00'),
('Globo fecha acordo para transmissão exclusiva da Copa do Mundo 2030', 'Emissora garante direitos de transmissão para todas as plataformas.', 'Tiago Leifert', '2025-03-30 14:20:00', '2025-03-30 14:20:00'),
('Programa de culinária da Globo lança linha de produtos', 'Utensílios e ingredientes do "Mais Você" estarão disponíveis em todo o país.', 'Ana Maria Braga', '2024-11-10 09:45:00', '2024-11-10 09:45:00'),
('Diretor da Globo recebe prêmio Lifetime Achievement em Hollywood', 'Trajetória de 40 anos na teledramaturgia brasileira é reconhecida internacionalmente.', 'Jayme Monjardim', '2025-01-30 18:20:00', '2025-01-30 18:20:00'),
('Globo lança canal exclusivo para esportes olímpicos', 'Nova plataforma funcionará 24 horas por dia com foco em modalidades menos conhecidas.', 'Tadeu Schmidt', '2024-09-25 13:45:00', '2024-10-15 16:30:00'),
('Novela da Globo aborda tema controverso e gera debate nacional', 'Trama sobre questões bioéticas provoca discussões em todos os setores da sociedade.', 'Manuela Dias', '2025-03-10 20:30:00', '2025-03-18 12:45:00'),
('GloboNews celebra 30 anos com programação especial', 'Canal de notícias apresenta retrospectiva dos principais acontecimentos das últimas três décadas.', 'Cristiane Pelajo', '2024-12-05 09:30:00', '2024-12-05 09:30:00'),
('Reality show de talentos da Globo descobre novo fenômeno musical', 'Vencedor do programa assina contrato com gravadora internacional.', 'Ivete Sangalo', '2025-02-05 21:40:00', '2025-02-06 10:15:00'),
('Série de ficção científica da Globo é comparada a produções de Hollywood', 'Críticos internacionais elogiam efeitos especiais e roteiro de produção nacional.', 'José Padilha', '2024-11-15 16:20:00', '2024-12-10 09:30:00'),
('Plataforma de educação da Globo chega a 5 milhões de estudantes', 'Ferramenta gratuita de apoio escolar completa um ano de funcionamento.', 'Luciano Huck', '2025-01-12 11:30:00', '2025-01-12 11:30:00'),
('Humorístico da Globo volta após 15 anos', 'Programa clássico retorna com elenco original e novas estrelas da comédia.', 'Paulo Gustavo', '2024-10-30 20:45:00', '2024-10-30 22:30:00'),
('Novo logotipo da Globo é revelado em evento transmitido mundialmente', 'Mudança na identidade visual marca nova fase da emissora.', 'João Roberto Marinho', '2025-02-01 19:00:00', '2025-02-01 21:30:00'),
('Globo lança iniciativa de sustentabilidade para todas as produções', 'Emissora se compromete a ter todas as gravações com carbono zero até 2030.', 'Marina Silva', '2025-04-22 10:15:00', '2025-04-22 10:15:00'),
('Filme produzido pelos Estúdios Globo é selecionado para Festival de Cannes', 'Longa-metragem dirigido por cineasta brasileiro concorre à Palma de Ouro.', 'Fernanda Montenegro', '2025-05-10 14:30:00', '2025-05-20 09:45:00'),
('Tecnologia desenvolvida pela Globo permite transmissões em qualidade inédita', 'Nova resolução ultrapassa padrões internacionais de definição de imagem.', 'Claudio Chaves', '2024-11-08 15:20:00', '2024-12-01 11:30:00'),
('Série dramática da Globo sobre pandemia emociona público', 'Produção baseada em histórias reais homenageia profissionais de saúde.', 'Regina Casé', '2024-12-15 18:30:00', '2025-01-10 14:45:00'),
('Globo Play atinge marca de 50 milhões de usuários ativos', 'Plataforma de streaming torna-se a mais utilizada no Brasil.', 'Carlos Henrique Schroder', '2025-03-15 12:00:00', '2025-03-15 12:00:00'),
('Programa de entrevistas da Globo recebe líder mundial em estreia', 'Primeira edição da atração conta com entrevista exclusiva com personalidade internacional.', 'Pedro Bial', '2024-09-20 21:30:00', '2024-09-20 23:15:00'),
('Novela da Globo é adaptada para o teatro e vira sucesso de público', 'Versão teatral esgota ingressos para toda a temporada no dia de lançamento.', 'Walcyr Carrasco', '2025-01-18 10:45:00', '2025-02-05 14:30:00'),
('Concurso de jornalismo da Globo revela novos talentos', 'Vencedores ganham oportunidade de trabalhar na emissora.', 'Cesar Tralli', '2025-04-25 09:30:00', '2025-05-10 16:45:00'),
('Globo inaugura maior estúdio virtual da América Latina', 'Tecnologia de ponta permitirá criar cenários totalmente virtuais para programas e novelas.', 'Silvio de Abreu', '2024-11-30 14:15:00', '2024-11-30 14:15:00'),
('Cobertura jornalística da Globo sobre desastre natural recebe prêmio internacional', 'Equipe é reconhecida por reportagens em áreas de difícil acesso.', 'Sandra Annenberg', '2025-02-28 13:20:00', '2025-02-28 18:45:00'),
('Programa de auditório da Globo completa 40 anos no ar', 'Atração dominical celebra aniversário com edição especial de 6 horas.', 'Fausto Silva', '2024-10-12 16:00:00', '2024-10-12 22:30:00'),
('Globo assina acordo com plataforma internacional de streaming', 'Novelas e séries brasileiras estarão disponíveis para público estrangeiro.', 'Alberto Pecegueiro', '2025-03-05 11:30:00', '2025-03-05 11:30:00'),
('Programa matinal da Globo renova formato e equipe', 'Nova temporada começa com cenário reformulado e novos quadros.', 'Patricia Poeta', '2024-08-25 08:15:00', '2024-09-10 07:30:00'),
('Globo lança universidade corporativa para formação de novos talentos', 'Iniciativa oferecerá cursos gratuitos em todas as áreas da comunicação.', 'Ricardo Waddington', '2025-01-20 13:45:00', '2025-01-20 13:45:00'),
('Telenovela da Globo é exibida simultaneamente em 25 países', 'Fenômeno da teledramaturgia brasileira conquista público internacional.', 'Gloria Perez', '2024-12-05 21:00:00', '2025-02-10 15:30:00'),
('Aplicativo de segunda tela da Globo permite interação em tempo real', 'Espectadores podem participar de enquetes e jogos durante a programação.', 'Zeca Camargo', '2025-02-15 19:45:00', '2025-02-15 19:45:00'),
('Documentário produzido pela Globo vence Festival de Berlim', 'Obra sobre diversidade cultural brasileira recebe Urso de Ouro.', 'João Moreira Salles', '2025-02-20 10:30:00', '2025-02-22 15:20:00'),
('Central de meteorologia da Globo prevê fenômeno climático inédito', 'Alerta emitido com antecedência ajuda autoridades a prevenir desastres.', 'Maria Júlia Coutinho', '2025-01-05 18:30:00', '2025-01-05 18:30:00'),
('Globo lança programa de mentoria para roteiristas iniciantes', 'Projeto visa descobrir e desenvolver novos talentos da dramaturgia nacional.', 'Benedito Ruy Barbosa', '2024-10-01 14:00:00', '2024-11-15 09:30:00'),
('Telejornal regional da Globo é premiado por cobertura comunitária', 'Série de reportagens sobre transformação de bairro periférico ganha destaque.', 'Fátima Bernardes', '2025-04-10 19:30:00', '2025-04-10 19:30:00'),
('Novo programa de gastronomia da Globo reúne chefs internacionais', 'Competição culinária traz técnicas de 15 países diferentes.', 'Claude Troisgros', '2025-03-01 20:00:00', '2025-03-15 20:45:00'),
('Globo fecha parceria com maior empresa de jogos do mundo', 'Personagens de novelas ganharão versões em videogames de sucesso.', 'Tiago Leifert', '2024-09-18 11:45:00', '2024-09-18 11:45:00'),
('Campanha publicitária da Globo vence Leão em Cannes', 'Peça sobre diversidade na televisão brasileira é reconhecida no festival de publicidade.', 'Roberto Marinho Neto', '2025-06-20 16:30:00', '2025-06-20 16:30:00'),
('Programa científico da Globo explica complexo fenômeno físico', 'Apresentadores usam experimentos ao vivo para demonstrar conceitos avançados.', 'Marcelo Gleiser', '2025-02-12 15:40:00', '2025-02-12 15:40:00'),
('Nova sede da Globo em São Paulo é modelo de sustentabilidade', 'Edifício utiliza energia 100% renovável e sistema avançado de reuso de água.', 'Paulo Marinho', '2025-05-15 09:00:00', '2025-05-15 09:00:00'),
('Globo lança divisão de realidade virtual para novas experiências', 'Espectadores poderão "entrar" nas cenas de novelas usando óculos VR.', 'José Roberto Maciel', '2024-11-20 13:15:00', '2025-01-15 16:30:00'),
('Musical da Globo homenageia grandes nomes da MPB', 'Espetáculo reúne estrelas da música brasileira em apresentação histórica.', 'Roberto Medina', '2025-04-05 21:30:00', '2025-04-05 21:30:00'),
('Seleção brasileira de futebol feminino é destaque na cobertura da Globo', 'Canal dedica programação especial para Campeonato Mundial.', 'Fernanda Gentil', '2025-07-15 16:00:00', '2025-07-15 16:00:00'),
('Edição especial de telejornal da Globo bate recorde de duração', 'Cobertura de evento político se estende por 7 horas ininterruptas.', 'Renata Lo Prete', '2024-10-28 19:00:00', '2024-10-29 02:15:00'),
('Série de animação da Globo é vendida para 40 países', 'Produção infantil brasileira conquista mercados na Ásia e Europa.', 'Mauricio de Sousa', '2025-03-22 10:30:00', '2025-03-22 10:30:00'),
('Globo lança plataforma exclusiva para conteúdo jornalístico premium', 'Assinantes terão acesso a reportagens especiais e análises aprofundadas.', 'Ali Kamel', '2024-12-18 11:45:00', '2025-02-05 14:30:00'),
('Campeonato estadual transmitido pela Globo tem audiência surpreendente', 'Final de torneio regional supera média de grandes eventos esportivos.', 'Luis Roberto', '2025-05-25 16:45:00', '2025-05-25 16:45:00'),
('Globo inaugura centro de pesquisa em inteligência artificial', 'Laboratório desenvolverá novas tecnologias para produção audiovisual.', 'Jorge Nóbrega', '2025-01-30 10:00:00', '2025-01-30 10:00:00'),
('Artistas exclusivos da Globo participam de turnê nacional', 'Show reúne atores e músicos em apresentação que percorrerá 15 capitais.', 'Fábio Porchat', '2024-11-15 19:30:00', '2025-02-28 21:15:00'),
('Globo lança canal internacional em novo continente', 'Programação brasileira chega oficialmente a países da Oceania.', 'Luiz Eduardo Baptista', '2025-04-15 09:45:00', '2025-04-15 09:45:00'),
('Formato inovador de programa da Globo é comprado por emissoras estrangeiras', 'Cinco países adquirem direitos para reproduzir atração brasileira.', 'Rodrigo Dourado', '2024-10-10 14:15:00', '2024-10-10 14:15:00'),
('Telejornal da Globo passa a ser apresentado por avatar digital', 'Tecnologia de IA permite criação de apresentador virtual para boletins noturnos.', 'César Filho', '2025-06-01 22:00:00', '2025-06-01 22:00:00'),
('Nova temporada de série da Globo é filmada em três continentes', 'Produção ambiciosa conta com locações no Brasil, Ásia e Europa.', 'Amora Mautner', '2025-03-10 15:30:00', '2025-03-10 15:30:00'),
('Time de eSports patrocinado pela Globo vence campeonato mundial', 'Equipe brasileira conquista título inédito em competição de jogos eletrônicos.', 'Nyvi Estephan', '2025-05-18 20:45:00', '2025-05-18 23:15:00'),
('Programa de debates da Globo inova com uso de realidade aumentada', 'Tecnologia permite visualização de dados complexos durante discussões.', 'Aline Midlej', '2025-02-05 21:30:00', '2025-02-05 21:30:00'),
('Prêmio de jornalismo da Globo recebe recorde de inscrições', 'Mais de 15 mil trabalhos concorrem em 20 categorias diferentes.', 'Cesar Tralli', '2025-01-15 09:45:00', '2025-01-15 09:45:00'),
('Sinal da Globo chega a área remota da Amazônia', 'Projeto social leva informação e entretenimento a comunidades isoladas.', 'Marcos Palmeira', '2024-09-15 11:20:00', '2024-10-05 14:30:00'),
('Série histórica da Globo reconstrói digitalmente cidades antigas', 'Técnica de computação gráfica permite recriação fiel de ambientes do século XIX.', 'Luiz Fernando Carvalho', '2025-05-05 16:15:00', '2025-05-05 16:15:00'),
('Globo lança festival de música e cultura em plataformas digitais', 'Evento online reúne artistas de todas as regiões do Brasil.', 'Regina Casé', '2025-03-25 18:30:00', '2025-03-25 18:30:00'),
('Tecnologia desenvolvida pela Globo permite customização da programação', 'Espectadores podem escolher entre diferentes ângulos de câmera em transmissões ao vivo.', 'Sergio Valente', '2024-12-05 15:20:00', '2025-01-10 11:45:00'),
('Remake de clássico da Globo surpreende com abordagem contemporânea', 'Nova versão de novela dos anos 80 aborda temas atuais mantendo essência original.', 'Daniel Ortiz', '2025-01-28 21:00:00', '2025-01-28 21:00:00'),
('Parceria entre Globo e universidades cria programa de bolsas', 'Iniciativa financiará pesquisas em comunicação e tecnologia audiovisual.', 'Marco Rodrigues', '2025-02-15 10:30:00', '2025-04-01 14:20:00'),
('Globo transmite ao vivo fenômeno astronômico raro', 'Cobertura especial de eclipse solar atinge pico de audiência em horário alternativo.', 'Cássio Barbosa', '2025-04-08 15:45:00', '2025-04-08 15:45:00'),
('Estudo revela impacto cultural das novelas da Globo', 'Pesquisa acadêmica analisa influência da teledramaturgia nos costumes brasileiros.', 'Aguinaldo Silva', '2024-11-20 09:30:00', '2024-11-20 09:30:00'),
('Novo quadro de programa dominical da Globo revela talentos do interior', 'Atração percorre cidades pequenas em busca de artistas desconhecidos.', 'Angélica', '2025-03-16 19:00:00', '2025-05-25 19:45:00'),
('Documentário investigativo da Globo revela esquema internacional', 'Trabalho jornalístico de dois anos resulta em repercussão global.', 'Caco Barcellos', '2025-02-10 21:30:00', '2025-02-10 21:30:00'),
('App de receitas da Globo alcança 10 milhões de downloads', 'Plataforma reúne pratos apresentados em diversos programas da emissora.', 'Ana Maria Braga', '2025-01-20 10:15:00', '2025-01-20 10:15:00'),
('Globo lança canal exclusivo para conteúdo nostálgico', 'Programação dedicada a reprises de produções clássicas da emissora.', 'Silvio de Abreu', '2024-10-15 14:30:00', '2024-10-15 14:30:00'),
('Inovação tecnológica permite que Globo transmita em áreas sem sinal', 'Sistema via satélite leva programação a regiões de difícil acesso.', 'Raymundo Barros', '2025-05-12 09:45:00', '2025-06-01 13:20:00'),
('Projeto social da Globo forma jovens cineastas na periferia', 'Iniciativa já revelou talentos que hoje trabalham em grandes produções.', 'Fernando Meirelles', '2024-09-30 11:15:00', '2024-09-30 11:15:00'),
('Novela da Globo inclui personagem com inteligência artificial', 'Trama futurista discute ética e limites da tecnologia no cotidiano.', 'João Emanuel Carneiro', '2025-02-03 20:00:00', '2025-02-03 20:00:00'),
('Globo estreia cobertura esportiva com tecnologia holográfica', 'Comentaristas aparecem no estúdio em forma de holograma durante transmissão.', 'Galvão Bueno', '2025-04-20 16:15:00', '2025-04-20 16:15:00'),
('Canal de notícias da Globo passa a transmitir 24 horas em 4K', 'GloboNews se torna o primeiro canal jornalístico brasileiro em ultra alta definição.', 'Miguel Athayde', '2024-11-01 08:30:00', '2024-12-15 12:40:00'),
('Programa de humor da Globo lança turnê internacional', 'Elenco fará apresentações em países de língua portuguesa.', 'Paulo Gustavo', '2025-03-30 15:45:00', '2025-03-30 15:45:00'),
('Especial da Globo sobre história brasileira é adotado em escolas', 'Documentário em cinco episódios se torna material didático oficial.', 'Laurentino Gomes', '2024-10-05 14:30:00', '2025-01-10 09:15:00');



-- Inserindo dados fictícios para a tabela content
INSERT INTO content (name, description, type, url) VALUES 
('Verdades Secretas III', 'Terceira temporada da aclamada série sobre o mundo da moda e suas obscuridades', 'novel', 'https://globoplay.com/verdades-secretas-3'),
('Avenida Brasil - Edição Especial', 'Reedição da novela com cenas inéditas e comentários do diretor', 'novel', 'https://globoplay.com/avenida-brasil-especial'),
('Documentário: Amazônia - O Último Refúgio', 'Documentário premiado sobre a maior floresta tropical do mundo', 'video', 'https://globoplay.com/amazonia-ultimo-refugio'),
('Master Chef Brasil - Temporada 10', 'Décima temporada do reality show de culinária mais famoso do país', 'video', 'https://globoplay.com/masterchef-10'),
('O Tempo Não Para - Série Completa', 'Todos os episódios da novela sobre viajantes do tempo', 'novel', 'https://globoplay.com/o-tempo-nao-para'),
('Jornal Nacional - Retrospectiva 2024', 'Compilação dos principais acontecimentos noticiados no ano anterior', 'video', 'https://globoplay.com/jn-retrospectiva-2024'),
('Nas Garras da Patrulha', 'Reality show que acompanha o dia a dia de policiais em diversas cidades brasileiras', 'video', 'https://globoplay.com/nas-garras-da-patrulha'),
('Amor de Mãe - Coleção Completa', 'Todos os capítulos da premiada novela sobre maternidade e suas complexidades', 'novel', 'https://globoplay.com/amor-de-mae-completa'),
('The Voice Brasil - Melhores Apresentações', 'Compilação das apresentações mais marcantes do programa musical', 'video', 'https://globoplay.com/the-voice-melhores'),
('Pantanal 2025', 'Remake da clássica novela ambientada no coração do Brasil', 'novel', 'https://globoplay.com/pantanal-2025'),
('Sob Pressão - Nova Temporada', 'Série médica que retrata os desafios da saúde pública no Brasil', 'novel', 'https://globoplay.com/sob-pressao-nova'),
('Pequenas Empresas, Grandes Negócios - Especial Startups', 'Documentário sobre o ecossistema de startups brasileiro', 'video', 'https://globoplay.com/pegn-startups'),
('A Força do Querer - Edição Estendida', 'Versão com cenas inéditas da aclamada novela de Glória Perez', 'novel', 'https://globoplay.com/forca-querer-estendida'),
('Esporte Espetacular - Olimpíadas Especial', 'Melhores momentos e histórias dos atletas olímpicos brasileiros', 'video', 'https://globoplay.com/ee-olimpiadas'),
('Império - Versão do Diretor', 'A saga da família de José Alfredo com comentários e cenas exclusivas', 'novel', 'https://globoplay.com/imperio-diretor'),
('Profissão Repórter: Investigações Completas', 'Coletânea das reportagens mais impactantes do programa jornalístico', 'video', 'https://globoplay.com/profissao-reporter-investigacoes'),
('Senhora do Destino - Remasterizada', 'Clássica novela com qualidade de imagem e som aprimorados', 'novel', 'https://globoplay.com/senhora-destino-remasterizada'),
('Globo Repórter: Mistérios do Cosmos', 'Série especial sobre descobertas astronômicas recentes', 'video', 'https://globoplay.com/gr-cosmos'),
('A Regra do Jogo - Integral', 'Todos os capítulos da trama de João Emanuel Carneiro sobre crime organizado', 'novel', 'https://globoplay.com/regra-jogo-integral'),
('Conversa com Bial - Entrevistas Históricas', 'Compilação das entrevistas mais marcantes do programa', 'video', 'https://globoplay.com/bial-entrevistas'),
('Totalmente Demais - Retrospectiva', 'Relembre a história de Eliza e Arthur com comentários do elenco', 'novel', 'https://globoplay.com/totalmente-demais-retro'),
('Caldeirão: Jogos Impossíveis', 'Reality show de competição com desafios extremos', 'video', 'https://globoplay.com/caldeirao-jogos'),
('Babilônia - Versão Estendida', 'Novela com cenas inéditas e finais alternativos', 'novel', 'https://globoplay.com/babilonia-estendida'),
('Que História é Essa, Porchat? - Melhores Momentos', 'As histórias mais surpreendentes contadas por celebridades', 'video', 'https://globoplay.com/porchat-melhores'),
('A Lei do Amor - Edição Completa', 'Todos os episódios da novela sobre vingança e redenção', 'novel', 'https://globoplay.com/lei-amor-completa'),
('Fantástico: Investigações Especiais', 'Série de grandes reportagens investigativas do programa dominical', 'video', 'https://globoplay.com/fantastico-investigacoes'),
('Êta Mundo Bom! - Remasterizado', 'Novela de época com Sergio Guizé em versão aprimorada', 'novel', 'https://globoplay.com/eta-mundo-bom-remasterizado'),
('Encontro com Fátima: Debates Essenciais', 'Compilação dos debates mais importantes do programa matinal', 'video', 'https://globoplay.com/encontro-debates'),
('Rock Story - Trilha Completa', 'A saga do mundo do rock nacional com todas as músicas originais', 'novel', 'https://globoplay.com/rock-story-completa'),
('Globo Esporte - Copas do Mundo', 'Especial com os melhores momentos das Copas do Mundo', 'video', 'https://globoplay.com/ge-copas'),
('Órfãos da Terra - Saga Integral', 'A história completa dos refugiados sírios em busca de uma nova vida', 'novel', 'https://globoplay.com/orfaos-terra-integral'),
('Lady Night - Temporadas Completas', 'Talk show de Tatá Werneck com todas as temporadas', 'video', 'https://globoplay.com/lady-night-completo'),
('O Outro Lado do Paraíso - Directors Cut', 'Versão do diretor da novela de Walcyr Carrasco', 'novel', 'https://globoplay.com/outro-lado-paraiso-dc'),
('Globo Rural - Especial Agronegócio', 'Série sobre inovações e desafios do agronegócio brasileiro', 'video', 'https://globoplay.com/rural-agronegocio'),
('Malhação - Coletânea Histórica', 'Os melhores momentos das 25 temporadas da série juvenil', 'novel', 'https://globoplay.com/malhacao-historica'),
('Altas Horas - Especial MPB', 'Edições dedicadas aos grandes nomes da música popular brasileira', 'video', 'https://globoplay.com/altas-horas-mpb'),
('A Dona do Pedaço - Versão Estendida', 'Novela com Maria da Paz em versão com cenas inéditas', 'novel', 'https://globoplay.com/dona-pedaco-estendida'),
('GloboNews Documento: Política Brasileira', 'Série documental sobre os bastidores do poder no Brasil', 'video', 'https://globoplay.com/gnews-politica'),
('Salve-se Quem Puder - Coleção Completa', 'A divertida história das três mulheres no programa de proteção', 'novel', 'https://globoplay.com/salve-se-completa'),
('Sem Censura - Entrevistas Exclusivas', 'As melhores entrevistas do tradicional programa de debates', 'video', 'https://globoplay.com/sem-censura-entrevistas'),
('Além do Tempo - Versão do Diretor', 'Romance que atravessa séculos com cenas adicionais', 'novel', 'https://globoplay.com/alem-tempo-diretor'),
('Domingão com Huck - Shows Completos', 'Apresentações musicais exclusivas do programa dominical', 'video', 'https://globoplay.com/domingao-shows'),
('Boogie Oogie - Remasterizada', 'Novela ambientada nos anos 70 com qualidade aprimorada', 'novel', 'https://globoplay.com/boogie-oogie-remasterizada'),
('Pequenas Empresas & Grandes Negócios - Série Empreendedores', 'Histórias inspiradoras de empreendedores brasileiros', 'video', 'https://globoplay.com/pegn-empreendedores'),
('Bom Sucesso - Edição Especial', 'A história de amor pela literatura em versão estendida', 'novel', 'https://globoplay.com/bom-sucesso-especial'),
('Globo Ciência - Descobertas Brasileiras', 'Série sobre avanços científicos desenvolvidos no Brasil', 'video', 'https://globoplay.com/ciencia-brasileira'),
('Tempo de Amar - Versão Integral', 'Romance de época ambientado em Portugal e Brasil', 'novel', 'https://globoplay.com/tempo-amar-integral'),
('Casos de Família - Histórias Reais', 'Os casos mais impressionantes do programa de histórias reais', 'video', 'https://globoplay.com/casos-familia-reais'),
('Pega Pega - Edição do Diretor', 'A trama policial do roubo ao hotel com cenas inéditas', 'novel', 'https://globoplay.com/pega-pega-diretor'),
('Mais Você - Receitas Completas', 'Coletânea das melhores receitas do programa matinal', 'video', 'https://globoplay.com/mais-voce-receitas'),
('Sol Nascente - Versão Estendida', 'A saga familiar com influências da cultura japonesa', 'novel', 'https://globoplay.com/sol-nascente-estendida'),
('Globo Universidade - Fronteiras da Ciência', 'Série sobre pesquisas de ponta nas universidades brasileiras', 'video', 'https://globoplay.com/universidade-ciencia'),
('A Vida da Gente - Remasterizada', 'Drama familiar com qualidade de imagem e som aprimorados', 'novel', 'https://globoplay.com/vida-gente-remasterizada'),
('Jornal Hoje - Economia Explicada', 'Série especial de reportagens sobre economia brasileira', 'video', 'https://globoplay.com/jh-economia'),
('Espelho da Vida - Edição Especial', 'Drama sobrenatural com cenas exclusivas', 'novel', 'https://globoplay.com/espelho-vida-especial'),
('Estrelas - Entrevistas Exclusivas', 'Angélica conversa com grandes nomes da televisão brasileira', 'video', 'https://globoplay.com/estrelas-entrevistas'),
('O Sétimo Guardião - Mistérios Revelados', 'A trama mística com conteúdo adicional explicando os enigmas', 'novel', 'https://globoplay.com/setimo-guardiao-misterios'),
('Bem Estar - Saúde Completa', 'Guia completo sobre saúde e bem-estar do programa matinal', 'video', 'https://globoplay.com/bem-estar-saude'),
('Verão 90 - Nostalgia Total', 'A divertida novela ambientada nos anos 90', 'novel', 'https://globoplay.com/verao-90-nostalgia'),
('Como Será? - Projetos Sociais', 'Reportagens sobre iniciativas que transformam comunidades', 'video', 'https://globoplay.com/como-sera-projetos'),
('Haja Coração - Versão Estendida', 'Reboot de Sassaricando com cenas inéditas', 'novel', 'https://globoplay.com/haja-coracao-estendida'),
('Jornal da Globo - Análises Econômicas', 'Série de reportagens aprofundadas sobre economia global', 'video', 'https://globoplay.com/jg-economia'),
('Alto Astral - Edição Completa', 'A história do médium Caíque e seu romance com Laura', 'novel', 'https://globoplay.com/alto-astral-completa'),
('Esporte Fantástico - Histórias de Superação', 'Perfis de atletas que superaram grandes desafios', 'video', 'https://globoplay.com/esporte-fantastico-superacao'),
('I Love Paraisópolis - Remasterizada', 'Romance ambientado na comunidade paulistana em alta definição', 'novel', 'https://globoplay.com/paraisopolis-remasterizada'),
('Esquenta! - Melhores Momentos', 'Os encontros musicais mais memoráveis do programa de Regina Casé', 'video', 'https://globoplay.com/esquenta-melhores'),
('Geração Brasil - Versão Estendida', 'A saga tecnológica com cenas exclusivas', 'novel', 'https://globoplay.com/geracao-brasil-estendida'),
('Superstar - Shows Completos', 'Apresentações na íntegra das bandas do reality musical', 'video', 'https://globoplay.com/superstar-shows'),
('Além do Horizonte - Mistérios Revelados', 'A comunidade secreta de Tereza Cristina com documentários extras', 'novel', 'https://globoplay.com/alem-horizonte-misterios'),
('É de Casa - Especial Decoração', 'Guia completo de reforma e decoração do programa matinal', 'video', 'https://globoplay.com/e-de-casa-decoracao'),
('Joia Rara - Edição Especial', 'A saga familiar com influências do budismo em versão estendida', 'novel', 'https://globoplay.com/joia-rara-especial'),
('Som Brasil - Especiais Completos', 'Shows dedicados aos grandes nomes da música brasileira', 'video', 'https://globoplay.com/som-brasil-especiais'),
('Sangue Bom - Versão Estendida', 'A busca de Bento por sua mãe biológica com cenas inéditas', 'novel', 'https://globoplay.com/sangue-bom-estendida'),
('TV Xuxa - Programa Completo', 'Edições na íntegra do programa infantil com a rainha dos baixinhos', 'video', 'https://globoplay.com/tv-xuxa-completo'),
('Cheias de Charme - Remasterizada', 'A saga das empreguetes em alta definição', 'novel', 'https://globoplay.com/cheias-charme-remasterizada'),
('Video Show - Momentos Históricos', 'Os bastidores mais marcantes da televisão brasileira', 'video', 'https://globoplay.com/video-show-historico'),
('Lado a Lado - Edição Especial', 'A novela histórica sobre o Rio de Janeiro do início do século XX', 'novel', 'https://globoplay.com/lado-lado-especial'),
('Popstar - Apresentações Completas', 'Shows na íntegra do reality musical com celebridades', 'video', 'https://globoplay.com/popstar-apresentacoes'),
('Cordel Encantado - Versão do Diretor', 'A mistura de conto de fadas com o sertão nordestino', 'novel', 'https://globoplay.com/cordel-encantado-diretor'),
('Caldeirão do Huck - Desafios Emocionantes', 'As transformações mais impressionantes do programa de Luciano Huck', 'video', 'https://globoplay.com/caldeirao-desafios'),
('Insensato Coração - Edição Completa', 'A trama sobre ambição e vingança com todos os capítulos', 'novel', 'https://globoplay.com/insensato-coracao-completa'),
('Revista Eletrônica - Grandes Reportagens', 'Coletânea jornalística sobre temas de impacto social', 'video', 'https://globoplay.com/revista-reportagens'),
('Passione - Remasterizada', 'A saga italiana de Totó e Clara em alta definição', 'novel', 'https://globoplay.com/passione-remasterizada'),
('Mestre do Sabor - Receitas Gourmet', 'Todas as receitas apresentadas no reality culinário', 'video', 'https://globoplay.com/mestre-sabor-receitas'),
('Tempos Modernos - Versão Estendida', 'A novela futurista com cenas inéditas', 'novel', 'https://globoplay.com/tempos-modernos-estendida'),
('Tamanho Família - Jogos Completos', 'As competições mais divertidas entre famílias de celebridades', 'video', 'https://globoplay.com/tamanho-familia-jogos'),
('Viver a Vida - Edição Especial', 'A história de superação de Luciana em versão comentada', 'novel', 'https://globoplay.com/viver-vida-especial'),
('The Wall - Desafios Completos', 'Todos os episódios do game show de perguntas e respostas', 'video', 'https://globoplay.com/wall-desafios'),
('Caras & Bocas - Versão Integral', 'A comédia romântica de Walcyr Carrasco na íntegra', 'novel', 'https://globoplay.com/caras-bocas-integral'),
('Zero1 - Tecnologia e Games', 'O programa dedicado ao universo geek e tecnológico', 'video', 'https://globoplay.com/zero1-tecnologia'),
('Caminho das Índias - Remasterizada', 'A premiada novela sobre a cultura indiana em alta definição', 'novel', 'https://globoplay.com/caminho-indias-remasterizada'),
('Hipertensão - Desafios Radicais', 'Reality show de esportes radicais apresentado por Zeca Camargo', 'video', 'https://globoplay.com/hipertensao-desafios'),
('A Favorita - Edição Comentada', 'A trama de João Emanuel Carneiro com comentários do diretor', 'novel', 'https://globoplay.com/favorita-comentada'),
('Amor & Sexo - Debates Completos', 'As discussões mais importantes sobre relacionamentos do programa', 'video', 'https://globoplay.com/amor-sexo-debates'),
('Duas Caras - Versão Estendida', 'A história de Juvenal Antena com cenas inéditas', 'novel', 'https://globoplay.com/duas-caras-estendida'),
('Domingão do Faustão - Arquivo Histórico', 'Os momentos mais marcantes dos 30 anos do programa', 'video', 'https://globoplay.com/domingao-historico'),
('Paraíso Tropical - Edição Especial', 'A trama de Bebel e Olavo com material adicional', 'novel', 'https://globoplay.com/paraiso-tropical-especial'),
('Show da Virada - Festas Inesquecíveis', 'Os melhores shows dos especiais de Ano Novo', 'video', 'https://globoplay.com/show-virada-festas');

